edition = "2021"
unstable_features = true

comment_width = 100
error_on_line_overflow = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
max_width = 100
