[package]
name = "www-saffi"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
init-tracing-opentelemetry.workspace = true
tracing.workspace = true

[dependencies.tracing-subscriber]
workspace = true
features = ["env-filter"]
