[package]
name = "www-saffi-wtf"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
axum.workspace = true
axum-tracing-opentelemetry.workspace = true
tracing.workspace = true
www-saffi.workspace = true

[dependencies.tokio]
workspace = true
features = ["full"]
